name: build

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 13
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Test
      run: mvn test
    - name: Run SonarCloud
      run: mvn verify sonar:sonar
